* Todo
- [X] linum-mode is slow.
  replace (require 'linum) and (linum-mode 1) with (display-line-numbers-mode 1)
  and if I want globally:

  #+begin_src emacs-lisp
    (global-display-line-numbers-mode 1)
  #+end_src

- [ ] fix the '<s' problem. (require 'org-tempo)
- [ ] http://orgmode.org/elpa/ is discontinued.
      It's distributed by GNU Elpa
- [ ] spaceline is dead.
  replace with doom-modeline
  (add to elpa-packages, then '(doom-modeline-mode 1)'
- [ ] loading "server" after require is redundant
  simplify to:
  #+begin_src emacs-lisp
    (unless (server-running-p) (server-start))
  #+end_src
- [ ] defadvice is obsolete, use advice-add
  replace '(defadvice load-theme....' with

  #+begin_src emacs-lisp
    (defun clear-existing-themes ()
      (mapc #'disable-theme custom-enabled-themes))
    (advice-add 'load-theme :before #'clear-existing-themes)
    (load-theme 'tsdh-dark t)  ; t forces replacement
  #+end_src
- [ ] package.el is old.
  instead, use:

  #+begin_src 
  (require `use-package)
  (setq use-package-always-ensure t)
  #+end_src
- [ ] encoding overkill.
  remove all the old encoding stuff, and use:
    (set-language-environment "UTF-8")
    (set-default-coding-systems 'utf-8)

    this should be enough, but it needs testing
- [ ] normal-backup-enable-predicate doesn't exist.
  consider replacing my function with:
  #+begin_src emacs-lisp
    (defun me/my-backup-enable-predicate (name)
      (not (or (string-prefix-p "~/gdrive/" name)
	       (string-prefix-p "/some/other/directory/" name))))
    (setq backup-enable-predicate #'me/my-backup-enable-predicate)
  #+end_src
- [ ] consider replacing scroll-step 1 with pixel-scroll-precision-mode
- [ ] consider replacing projectile in favour of project.el
- [ ] consider using =repeat-mode=.
  Instead of typing c-x o c-x o to switch windows twice, I can type c-x o o.
- [ ] compile native machine code
  apparently I can compile to native machine code instead of just interpreting el files.
- [ ] move custom.el to top of the file
  since emacs's variables are available to my code.
- [ ] consider vertico+consult+marginaila
  inetad of counsel/swiper/ivy
- [ ] treemacs is slow
  consdicer eaf-browser or the built-in projectile-find-file
- [ ] instead of tide/js2-mode use eglot
  remove tide-js2-mode and add '(global-eglot-ensure)'
- [ ] mpg123 is unmaintained
- [ ] atomic-chrome is broken
- [ ] diff-hl is very very slow

After changes, M-x package-autoremove  


